### PR TITLE
rename main to entry-points

### PR DESCRIPTION
**Pull request by myguidingstar-zz**
The word "main" is quite confusing and as I consult @micha, he suggests the word "entry-point"

### CODE REVIEW

**Comment by Deraen** [comment]
I think this change should be pushed to upstream.

**Comment by myguidingstar-zz** [comment]
What about your changes so far?

**Comment by Deraen** [comment]
They should eventually be merged upstream but the changes here break some features and I haven't had time to think how they should be solved.

**Comment by Deraen** [comment]
:main is used by Cljs compiler: https://github.com/clojure/clojurescript/wiki/Compiler-Options#main

**Pull request closed without merging**
